import {
  html,
  css,
  javascript,
  typescript,
  reactjs,
  redux,
  tailwind,
  mui,
  threejs,
  framer,
  gsap,
  nodejs,
  express,
  mongodb,
  mysql,
  git,
  figma,
  python,
  c,
  cpp
} from '../assets';

export const techStacks = {
  frontend: [
    { name: "HTML 5", icon: html },
    { name: "CSS 3", icon: css },
    { name: "JavaScript", icon: javascript },
    { name: "TypeScript", icon: typescript },
    { name: "React JS", icon: reactjs },
    { name: "Next JS", icon: null },
    { name: "Redux Toolkit", icon: redux },
    { name: "Tailwind CSS", icon: tailwind },
    { name: "Material Ui", icon: mui },
    { name: "Three JS", icon: threejs },
    { name: "framer", icon: framer },
    { name: "gsap", icon: gsap },
  ],
  backend: [
    { name: "Node JS", icon: nodejs },
    { name: "Express Js", icon: express },
    { name: "Next JS", icon: null },
    { name: "Flask", icon: null },
    { name: "MongoDB", icon: mongodb },
    { name: "MySql", icon: mysql },
  ],
  other: [
    { name: "git", icon: git },
    { name: "figma", icon: figma },
    { name: "Python", icon: python },
    { name: "Java", icon: null },
    { name: "C", icon: c },
    { name: "C++", icon: cpp },
    { name: "OpenCV", icon: null },
  ]
};
